# Generated by Django 6.0.3 on 2026-04-02 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_transferred', models.PositiveIntegerField(default=1)),
                ('challan_number', models.CharField(max_length=50, unique=True)),
                ('transferred_by', models.CharField(max_length=100)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.product')),
                ('to_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.outlet')),
            ],
        ),
    ]
