# Generated by Django 6.0.3 on 2026-04-13 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_outlet_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Transfer History',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.transfer',),
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='outlet',
            options={'verbose_name_plural': 'Outlets'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'verbose_name_plural': 'Transfers'},
        ),
        migrations.AddField(
            model_name='transfer',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='assets.outlet'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='received_by',
            field=models.CharField(default='System', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to_outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='assets.outlet'),
        ),
        migrations.CreateModel(
            name='OutletStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.outlet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.product')),
            ],
            options={
                'verbose_name_plural': 'Outlet Stocks',
                'unique_together': {('outlet', 'product')},
            },
        ),
    ]
